c/*
c* Polylib - Polygon Management Library
c*
c* Copyright (c) 2010-2011 VCAD System Research Program, RIKEN.
c* All rights reserved.
c*
c* Copyright (c) 2012-2016 Advanced Institute for Computational Science, RIKEN.
c* All rights reserved.
c*
c*/

c*********************************************************
c
c Fortran77インクルードファイル
c    関数の型定義（単精度用）
c    Fortran77ユーザアプリ用のインクルードファイル
c    (Polylib内部はC++で実装されており当インクルードファイルは使用していない)
c
c    注意事項：単精度／倍精度によりインクルードするファイルを切り替えること
c
c*********************************************************

      real*4 fpolylib_triangle_get_atr
