c/*
c* Polylib - Polygon Management Library
c*
c* Copyright (c) 2010-2011 VCAD System Research Program, RIKEN.
c* All rights reserved.
c*
c* Copyright (c) 2012-2016 Advanced Institute for Computational Science, RIKEN.
c* All rights reserved.
c*
c*/

c*********************************************************
c
c Fortran77インクルードファイル
c    関数の型定義（整数用）
c    Fortran77ユーザアプリ用のインクルードファイル
c    (Polylib内部はC++で実装されており当インクルードファイルは使用していない)
c
c*********************************************************

      integer fpolylib_used_memory_size
      integer fpolylib_used_memory_size_mb
      integer fpolylib_triangle_get_pl_type
      integer fpolylib_triangle_get_atrI
