!/*
!* Polylib - Polygon Management Library
!*
!* Copyright (c) 2010-2011 VCAD System Research Program, RIKEN.
!* All rights reserved.
!*
!* Copyright (c) 2012-2016 Advanced Institute for Computational Science, RIKEN.
!* All rights reserved.
!*
!*/

!*********************************************************
!
! Fortranインクルードファイル
!    関数の型定義
!    Fortran90ユーザアプリ用のインクルードファイル
!    (Polylib内部はC++で実装されており当インクルードファイルは使用していない)
!
!*********************************************************

!----------------------------------------------------
! Fortranプロトタイプ
!----------------------------------------------------
  real(PL_REAL_PN)  fpolylib_triangle_get_atrR

  integer           fpolylib_used_memory_size
  integer           fpolylib_used_memory_size_mb
  integer           fpolylib_triangle_get_pl_type
  integer           fpolylib_triangle_get_atrI

